### ISSUE TITLE
Publish a tagged version with fix to set-env removal

### ISSUE THREAD

**Issue by antonincms** [actions-hub/docker#2]
Hello,

The set-env command seems to be finally disabled by github (cf https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ ). As v1.0.0 is still the latest release on the actions marketplace, would it be possible to tag another version instead of having to use `@master` ?

**Comment by exelban** [comment]
Hi. Thanks, I'm going to make a new tag.

**Comment by exelban** [comment]
Done. [v1.0.1](https://github.com/actions-hub/docker/releases/tag/v1.0.1)

**Comment by antonincms** [comment]
Thank you !
