### ISSUE TITLE
Release new version with SKIP_LOGIN fix

### ISSUE THREAD

**Issue by kierans** [actions-hub/docker#6]
Can a new version be released with the SKIP_LOGIN fix (cf: https://github.com/actions-hub/docker/pull/5)?

I prefer to refer to tagged versions of actions in my workflows.

**Comment by exelban** [comment]
Hi. Yeap, sorry for that.

**Comment by kierans** [comment]
@exelban Thanks for your reply. I just checked the tags list, and there isn't a new one. Were you meaning to make one?

**Comment by exelban** [comment]
https://github.com/actions-hub/docker/releases/tag/v1.0.3
